//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my8.Assistant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TheText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TheText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("my8.Assistant.TheText", typeof(TheText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;AppendBusinessDI&gt;.
        /// </summary>
        internal static string AppendBusinessDI {
            get {
                return ResourceManager.GetString("AppendBusinessDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;AppendDbSetHere&gt;.
        /// </summary>
        internal static string AppendDbSetHere {
            get {
                return ResourceManager.GetString("AppendDbSetHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;AppendNewIHere&gt;.
        /// </summary>
        internal static string AppendIUoW {
            get {
                return ResourceManager.GetString("AppendIUoW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //AppendMongoDI.
        /// </summary>
        internal static string AppendMongoDI {
            get {
                return ResourceManager.GetString("AppendMongoDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //AppendNeoDI.
        /// </summary>
        internal static string AppendNeoDI {
            get {
                return ResourceManager.GetString("AppendNeoDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;AppendNewHere&gt;.
        /// </summary>
        internal static string AppendNewHere {
            get {
                return ResourceManager.GetString("AppendNewHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //AppendSqlDI.
        /// </summary>
        internal static string AppendSqlDI {
            get {
                return ResourceManager.GetString("AppendSqlDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;AppendNewHere&gt;.
        /// </summary>
        internal static string AppendUow {
            get {
                return ResourceManager.GetString("AppendUow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cs.
        /// </summary>
        internal static string CSharpFileExtension {
            get {
                return ResourceManager.GetString("CSharpFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {EFReturnType}.
        /// </summary>
        internal static string EFReturnType {
            get {
                return ResourceManager.GetString("EFReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;GenericCreate&gt;.
        /// </summary>
        internal static string GenericCreate {
            get {
                return ResourceManager.GetString("GenericCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;GenericFind&gt;.
        /// </summary>
        internal static string GenericFind {
            get {
                return ResourceManager.GetString("GenericFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;GenericFindById&gt;.
        /// </summary>
        internal static string GenericFindById {
            get {
                return ResourceManager.GetString("GenericFindById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;GenericGetAll&gt;.
        /// </summary>
        internal static string GenericGetAll {
            get {
                return ResourceManager.GetString("GenericGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;GenericRemove&gt;.
        /// </summary>
        internal static string GenericRemove {
            get {
                return ResourceManager.GetString("GenericRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;GenericRemoveById&gt;.
        /// </summary>
        internal static string GenericRemoveById {
            get {
                return ResourceManager.GetString("GenericRemoveById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;GenericUpdate&gt;.
        /// </summary>
        internal static string GenericUpdate {
            get {
                return ResourceManager.GetString("GenericUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {KeyType}.
        /// </summary>
        internal static string KeyType {
            get {
                return ResourceManager.GetString("KeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ModelClass][DapperMapping][EFMapping].
        /// </summary>
        internal static string ModelClass {
            get {
                return ResourceManager.GetString("ModelClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ModelName}.
        /// </summary>
        internal static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {modelname}.
        /// </summary>
        internal static string modelnameLowerCase {
            get {
                return ResourceManager.GetString("modelnameLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .php.
        /// </summary>
        internal static string PHPFileExtension {
            get {
                return ResourceManager.GetString("PHPFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;SqlCreate&gt;.
        /// </summary>
        internal static string SqlCreate {
            get {
                return ResourceManager.GetString("SqlCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;SqlFind&gt;.
        /// </summary>
        internal static string SqlFind {
            get {
                return ResourceManager.GetString("SqlFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;SqlFindById&gt;.
        /// </summary>
        internal static string SqlFindById {
            get {
                return ResourceManager.GetString("SqlFindById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;SqlGetAll&gt;.
        /// </summary>
        internal static string SqlGetAll {
            get {
                return ResourceManager.GetString("SqlGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;SqlRemove&gt;.
        /// </summary>
        internal static string SqlRemove {
            get {
                return ResourceManager.GetString("SqlRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;SqlRemoveById&gt;.
        /// </summary>
        internal static string SqlRemoveById {
            get {
                return ResourceManager.GetString("SqlRemoveById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //&lt;SqlUpdate&gt;.
        /// </summary>
        internal static string SqlUpdate {
            get {
                return ResourceManager.GetString("SqlUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {TableName}.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
    }
}
